# Generated by Django 3.0.8 on 2020-08-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='adhar',
        ),
        migrations.AddField(
            model_name='user',
            name='owner_ph_no',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_fuel',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_pol_status',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_location',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
