# Generated by Django 3.0.8 on 2020-08-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accident',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
